####################################################################################
## MAKEFILE
####################################################################################

PROJECT_NAME := uart_pmod1553_nexys-a7-100t

M_DEPS += ../common/uart_pmod1553_bd.tcl
M_DEPS += ../../common/nexys-a7-100t/nexys-a7-100t_system_constr.xdc
M_DEPS += ../../common/nexys-a7-100t/nexys-a7-100t_system_bd.tcl

LIB_DEPS += util_uart_1553_core

include ../../scripts/project-xilinx.mk
