####################################################################################
## MAKEFILE
####################################################################################

PROJECT_NAME := uart_pmod1553_cmod-s7-25

M_DEPS += ../common/uart_pmod1553_bd.tcl
M_DEPS += ../../common/cmod-s7-25/cmod-s7-25_system_constr.xdc
M_DEPS += ../../common/cmod-s7-25/cmod-s7-25_system_bd.tcl

LIB_DEPS += util_uart_1553_core

include ../../scripts/project-xilinx.mk
