####################################################################################
## MAKEFILE
####################################################################################

PROJECT_NAME := uart_pmod1553_arty-a7-35

M_DEPS += ../common/uart_pmod1553_bd.tcl
M_DEPS += ../../common/arty-a7-35/arty-a7-35_system_constr.xdc
M_DEPS += ../../common/arty-a7-35/arty-a7-35_system_bd.tcl

LIB_DEPS += util_uart_1553_core

include ../../scripts/project-xilinx.mk
